FROM node:18.16.0-slim as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM node:18.16.0-slim as final
WORKDIR /app
COPY --from=build /app .
COPY package.json .
COPY package-lock.json .
RUN npm install
EXPOSE 5001