version: '3'
services:
  server:
    command:
      - nodemon
      - --inspect=0.0.0.0:9229
      - --signal
      - SIGINT
      - --nolazy
      - src/index.ts
    image: server-image-dev:latest
    container_name: server-dev
    ports:
      - 9229:9229
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules